minVersion: 1.2.1
changelogPolicy: auto
targets:
  - name: maven
    gradleCliPath: ./gradlew
    mavenCliPath: scripts/mvnw
    mavenSettingsPath: scripts/settings.xml
    mavenRepoId: ossrh
    mavenRepoUrl: https://oss.sonatype.org/service/local/staging/deploy/maven2/
    android:
      distDirRegex: /^(sentry-android-|.*-android).*$/
      fileReplaceeRegex: /\d\.\d\.\d(-\w+(\.\d)?)?(-SNAPSHOT)?/
      fileReplacerStr: release.aar
    kmp:
      rootDistDirRegex: /^(?!.*(?:jvm|android|ios|watchos|tvos|macos)).*$/
      appleDistDirRegex: /(ios|watchos|tvos|macos)/
  - name: github
  - name: registry
    sdks:
      maven:io.sentry:sentry-kotlin-multiplatform:

