minVersion: 1.2.1
changelogPolicy: auto
targets:
  - name: maven
    id: kmp
    gradleCliPath: ./gradlew
    mavenCliPath: scripts/mvnw
    mavenSettingsPath: scripts/settings.xml
    mavenRepoId: ossrh
    mavenRepoUrl: https://oss.sonatype.org/service/local/staging/deploy/maven2/
    android:
      distDirRegex: /^(sentry-android-|.*-android).*$/
      fileReplaceeRegex: /\d+\.\d+\.\d+(-\w+(\.\d+)?)?(-SNAPSHOT)?/
      fileReplacerStr: release.aar
    kmp:
      rootDistDirRegex: /^(?!.*(?:jvm|android|ios|watchos|tvos|macos)).*$/
      appleDistDirRegex: /(ios|watchos|tvos|macos)/
    excludeNames: /sentry-kotlin-multiplatform-gradle-plugin.*$/
  - name: maven
    id: plugin
    gradleCliPath: ./gradlew
    mavenCliPath: scripts/mvnw
    mavenSettingsPath: scripts/settings.xml
    mavenRepoId: ossrh
    mavenRepoUrl: https://oss.sonatype.org/service/local/staging/deploy/maven2/
    android: false
    includeNames: /sentry-kotlin-multiplatform-gradle-plugin.*$/
  - name: github
  - name: registry
    sdks:
      maven:io.sentry:sentry-kotlin-multiplatform:
#      maven:io.sentry:sentry-kotlin-multiplatform-gradle-plugin:

