# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ios-cocoa' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ios-cocoa

  pod 'sentry_kotlin_multiplatform', :path => '../../'

end
