# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ios
  pod 'app', :path => '../app'
  pod 'Sentry', '~> 5.2.0'

end
