comments:
  UndocumentedPublicClass:
    active: true
    ignoreDefaultCompanionObject: true
    includes: "**/commonMain/**"
  UndocumentedPublicProperty:
    active: true
    includes: "**/commonMain/**"
style:
  UnnecessaryAbstractClass:
    active: false
  ForbiddenComment:
    active: false
  UnusedPrivateProperty:
    excludes:
      - "**/Attachment.kt"
  ReturnCount:
    active: false
naming:
  MatchingDeclarationName:
    active: false
complexity:
  TooManyFunctions:
    excludes: [
      "**/SentryKMP.kt",
      "**/SentryBridge.*",
      "**/CocoaScopeProvider.kt",
      "**/Scope.kt",
      "**/JvmScopeProvider.kt",
      "**/Breadcrumb.kt",
      "**/SentryLogger.kt",
      "**/BaseSentryLogger.kt",
      "**/NoOpSentryLogger.kt",
    ]
  LongMethod:
    excludes:
      - "**/SentryOptionsExtensions.*"
    
