name: "Analyze"
on:
  push:
    branches:
      - main
      - release/**
  pull_request:
    paths-ignore:
      - "**/*.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: JDK setup
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          java-version: 17
          distribution: temurin

      - name: Analyze
        run:
          ./gradlew apiCheck detekt spotlessCheck