# Disable for now until we bump the kotlin version

#name: Generate Dokka
#
#on:
#  release:
#    types: [released]
#
## Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
#permissions:
#  contents: read
#  pages: write
#  id-token: write
#
#jobs:
#  generate-dokka:
#    runs-on: ubuntu-latest
#    environment:
#      name: github-pages
#      url: ${{ steps.deployment.outputs.page_url }}
#    steps:
#      - name: Checkout
#        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
#
#      - name: set up JDK 11
#        uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4
#        with:
#          distribution: "adopt"
#          java-version: "11"
#
#      - name: Cache Gradle packages
#        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
#        with:
#          path: |
#            ~/.gradle/caches
#            ~/.gradle/wrapper
#          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
#          restore-keys: |
#            ${{ runner.os }}-gradle-
#
#      - name: Setup Pages
#        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5
#
#      - name: Generate docs with dokka
#        run: make generateDokka
#
#      - name: Upload artifact
#        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3
#        with:
#          path: ${{ github.workspace }}/build/dokka/htmlMultiModule
#
#      - name: Deploy to GitHub Pages
#        id: deployment
#        uses: actions/deploy-pages@f27bcc15848fdcdcc02f01754eb838e44bcf389b # v1
