name: "Integration Test"
on:
  push:
    branches:
      - main
      - release/**
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest-xlarge

    steps:
      - uses: actions/checkout@v4

      - name: JDK setup
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Cached Konan
        uses: actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7 #v3
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-konan-

      - name: Cached Gradle
        uses: gradle/gradle-build-action@842c587ad8aa4c68eeba24c396e15af4c2e9f30a

      - name: Update version
        run: |
          ./scripts/bump-version.sh 0 1.0.0-integration-test

      - name: Publish Maven Local
        run: |
          ./gradlew publishToMavenLocal

      - name: Build Integration Test
        run: |
          ./gradlew :integration-test:shared:assemble -PincludeIntegrationTest=true 
