name: Update Dependencies

on:
  schedule:
    - cron: '0 3 * * *'
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  actions: write

jobs:
  cocoa:
    runs-on: macos-15
    steps:
      - uses: getsentry/github-workflows/updater@607fed74f812e69201531a5185b6c3c57caa4e89 # v3
        with:
          path: scripts/update-cocoa.sh
          name: Cocoa SDK
          changelog-entry: true
          pr-strategy: update
          target-branch: main
          ssh-key: ${{ secrets.CI_DEPLOY_KEY }}

  java:
    runs-on: ubuntu-latest
    steps:
      - uses: getsentry/github-workflows/updater@607fed74f812e69201531a5185b6c3c57caa4e89 # v3
        with:
          path: scripts/update-java.sh
          name: Java SDK
          changelog-entry: true
          pr-strategy: update
          target-branch: main
          ssh-key: ${{ secrets.CI_DEPLOY_KEY }}
