name: "Generate and upload distributions"
on:
  push:
    branches:
      - release/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  archive-distribution:
    runs-on: macos-latest-xlarge

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: JDK setup
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          java-version: 17
          distribution: temurin

      - name: Cached Gradle
        uses: gradle/gradle-build-action@ac2d340dc04d9e1113182899e983b5400c17cda1

      - name: DistZip libraries
        run: |
          ./gradlew distZip

      - name: DistZip plugin
        run: |
          cd sentry-kotlin-multiplatform-gradle-plugin
          ./gradlew distZip sentryPluginMarkerDistZip validateDistributions

      - name: Validate distributions
        run: |
          ./gradlew validateDistributions

      - name: Archive packages
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ github.sha }}
          if-no-files-found: error
          path: |
            ./*/build/distributions/*.zip
